INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (1,'Crazy,Stupid,Love',6.0,59334);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (2,'Love, Simon',7.5,115270);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (3,'Love',5.4,8817);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (4,'Killer elite',6.4,130812);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (5,'Simon Killer',6.3,4794);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (6,'The Amazing Spider-Man 2',6.6,474218);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (7,'Spider-Man: No Way Home',8.7,473284);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (8,'Spider-Man: Into the Spider-Verse',8.4,473159);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (9,'Spider-Man: Far from Home',7.4,444812);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (10,'Marvel Rising: Secret Warriors',5.4,1345);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (11,'Captain Marvel',6.8,556045);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (12,'Kiss of the Spider Woman',7.3,15386);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (13,'Killer Legends',6.2,3403);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (14,'Code of a killer',7.6,3285);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (15,'The Spider Woman',7.0,4529);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (16,'The Giant Spider Invasion',3.2,4180);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (17,'Marvel 616',6.5,651);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (18,'Spider',7.7,2793);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (19,'Earth vs. the Spider',4.3,2162);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (20,'Bounty Killer',5.5,7268);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (21,'Spider in the Web',4.5,1660);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (22,'Spider-Plant Man',6.4,1557);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (23,'Jack Black: Spider-Man',7.5,1537);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (24,'The Red Spider',5.8,1415);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (25,'Starwars: Goretech',5.3,32);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (26,'Monmon the Water Spider',7.6,351);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (27,'Spider Man: Lost Cause',5.2,346);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (28,'Son en Zorro',7.2,29);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (29,'Zorro the Chronicles',7.7,96);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (30,'Montando al Zorro',0.0,0);
